//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingWebAPI2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting : iBaseWebModel
    {
        public long Id { get; set; }
        public string SettingName { get; set; }
        public string SettingValueStr { get; set; }
        public Nullable<bool> SettingValueBool { get; set; }
        public Nullable<double> SettingValueNumber { get; set; }
    }
}
