//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingWebAPI2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public long Id { get; set; }
        public double Amount { get; set; }
        public string Description { get; set; }
        public Nullable<long> PersonId { get; set; }
        public Nullable<long> AccountId { get; set; }
        public bool Executed { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ExecutionDate { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Person Person { get; set; }
    }
}
